"""empty message

Revision ID: 436e7a993e07
Revises: e4b8e9bb3c7e
Create Date: 2020-11-05 09:30:10.280939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436e7a993e07'
down_revision = 'e4b8e9bb3c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('youtuber', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('subscriber', sa.Integer(), nullable=False),
    sa.Column('imgAdr', sa.String(length=200), nullable=False),
    sa.Column('categori', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
