"""empty message

Revision ID: 4ecc22933767
Revises: 4f0ed16eb1a1
Create Date: 2020-11-05 09:09:32.196139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecc22933767'
down_revision = '4f0ed16eb1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('youtuber', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('subscriber', sa.Integer(), nullable=False),
    sa.Column('imgAdr', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
