"""empty message

Revision ID: 4f0ed16eb1a1
Revises: 3ea026e83245
Create Date: 2020-11-05 09:02:03.306293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0ed16eb1a1'
down_revision = '3ea026e83245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thumbnail', 'imgAdr',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail', 'subscriber',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('thumbnail', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail', 'youtuber',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_thumbnail_index', table_name='thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_thumbnail_index', 'thumbnail', ['index'], unique=False)
    op.alter_column('thumbnail', 'youtuber',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('thumbnail', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('thumbnail', 'subscriber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail', 'imgAdr',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
