"""empty message

Revision ID: 7664105d48bc
Revises: 9a0941b600af
Create Date: 2020-11-09 09:13:31.250591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7664105d48bc'
down_revision = '9a0941b600af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('youtuber', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('subscriber', sa.Integer(), nullable=False),
    sa.Column('imgAdr', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
