"""empty message

Revision ID: f70575a82228
Revises: e0ded9db2d0f
Create Date: 2020-11-12 17:00:56.025270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70575a82228'
down_revision = 'e0ded9db2d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thumbnail', 'category',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('thumbnail', 'imgAdr',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('thumbnail', 'score',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('thumbnail', 'subscriber',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('thumbnail', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail', 'youtuber',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_thumbnail_index', table_name='thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_thumbnail_index', 'thumbnail', ['index'], unique=False)
    op.alter_column('thumbnail', 'youtuber',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('thumbnail', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('thumbnail', 'subscriber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail', 'score',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('thumbnail', 'imgAdr',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('thumbnail', 'category',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
